### ISSUE TITLE
crdroid 9.2 gsi lenovo p 11 plus 616f

### ISSUE THREAD

**Issue by 13didounet** [naz664/crDroid_patches#10]
Cannot install 9.2.
Can't find google server.
No problem with other Gsi

**Comment by naz664** [comment]
Using gapps varient ?
Can you connect to internet properly ?
If not run this via terminal
adb shell settings put global restricted_networking_mode 0

**Comment by 13didounet** [comment]
Hello and thanks for the answer
crDroid-9.2-arm64_bgN-Unofficial.img.xz
dsu installed
list of wifi networks
Network selection
Display Wifi connected but stays on this page
I think the network is not found
I tried 2.4 and 5 same result
I have Arrow in the current system
I have tried other gsi and no problem

**Comment by naz664** [comment]
Run the command which i mentioned earlier and it would be fine ig

**Comment by 13didounet** [comment]
thank a lot Nazim for your great job and helpfull guidenneess

**Comment by naz664** [comment]
You're welcome

**Comment by Homi74** [comment]
One note about the Lenovo Tab P11 Plus "TB-J616F and J616X"
With all GSI builds, I had a problem with the device not being recognized after connecting to USB, adb not working either.
I've been working on how to fix this for a while and adding a single parameter to build.prop helped me.

ro.odm.lenovo.series=Lenovo Tab P11 Plus

After restarting and connecting to the PC with a USB cable, the tablet was recognized.
![Screenshot_20230405-223035_Spark Launcher](https://user-images.githubusercontent.com/69285725/230204775-022c4489-d429-4bf3-b807-04a6bf90e298.png)

**Comment by naz664** [comment]
Ok cool
