### ISSUE TITLE
Power button

### ISSUE THREAD

**Issue by ghost** [naz664/crDroid_patches#106]
I can't unlock my phone with power buttons. When I turn off my phone and press power button to turn it on - it doesn't. I can only do that with volume buttons(which I set in crdroid setting) any help? And also my NFC isn't working (not there in settings)But on a rom where I came from it was working fine

**Comment by SHUSHANT2384** [comment]
Yes some features of your phone turn off or may not work for eg the back light of nothing phones doesn't work on custom roms and this is why NFC isn't working
