### ISSUE TITLE
Question about Superuser access + something else

### ISSUE THREAD

**Issue by WhySooooFurious** [naz664/crDroid_patches#109]
I noticed that root access can be enabled through adb but can't actually be managed of course!

Is there any way to get an su app like phh's superuser?

If not i'll still be using the awesome rom,

p.s for some reason my device gets hot when streaming stremio and having the vid at full acceleration idk why but heating is the only problem when viewing the videos, other than that it works fine

**Comment by groszdaniel** [comment]
Magisk?

**Comment by WhySooooFurious** [comment]
This is installed through DSU Sideloader, sadly my Galaxy A12 isn't compatible with Magisk despite everything.

A known issue on XDA.
