### ISSUE TITLE
crDroid GSI 9.2 v2023.02.17 and rotation issue on Lenovo TB-J706L

### ISSUE THREAD

**Issue by IoSonoPiero** [naz664/crDroid_patches#11]
Hello,
I've tried a lot of GSI ROMs, but the crDroid-9.2-arm64_bgN-Unofficial.img.xz image worked without issue on the first attempt.
Everything works fine except for the screen rotation.
Whatever the physical screen orientation is, you got a -90 degree.

I've partially solved the issue by installing Orientation Control on Google Play and enabling the "lie left" option.
At boot (before the app starts) and when system dialog windows are shown on the screen, the orientation is -90.

The same issue happens with other GSI ROMs, too.

I'm available for tests or to provide the information requested.

**Comment by Tonyha7** [comment]
It might be a problem of TB-J706L. If you port TB-J706L's rom to other Lenovo tablets, there'll be a +90.

I guess the sensor is specific.

**Comment by IoSonoPiero** [comment]
I think it's surely a specific problem of this model. There is a way to fix this behaviour in crDroid?
For me, after more than 1 month of usage, there are no problems at all. I can contribute with a donation, of course.

**Comment by Tonyha7** [comment]
> I think it's surely a specific problem of this model. There is a way to fix this behaviour in crDroid? For me, after more than 1 month of usage, there are no problems at all. I can contribute with a donation, of course.

Sorry, I have no idea how to solve it on the system level. But you can modify frameworks/native/libs/ui/include/ui/Rotation.h and compile it. It's not a good idea, but it works.
