### ISSUE TITLE
[ REQUEST ] Add option to build slim version and sign with release-keys .

### ISSUE THREAD

**Issue by FreezyKaif-V2** [naz664/crDroid_patches#123]
In the recent days, it has become mandatory for custom rom builds to be signed with release-keys in order to pass Play Integrity  and also please add option to build slim image for GAPPS.

**Comment by naz664** [comment]
Latest builds were signed with release keys,
As for play integrity blame google.
You can set  "BOARD_EXT4_SHARE_DUP_BLOCKS := true"  on  device/phh/treble/board-base.mk to build slim varient with or without gapps
