### ISSUE TITLE
crDroid 10.11 refused to boot (reboots into recovery after vendor logo)

### ISSUE THREAD

**Issue by hrzndelta** [naz664/crDroid_patches#124]
after clean flashing the bgN-slim and bvN variants it refused to boot into system, instead it throws me into recovery
here are the logs:
[recovery.log](https://github.com/user-attachments/files/18198838/recovery.log)
[logcat.txt](https://github.com/user-attachments/files/18198839/logcat.txt)
[dmesg.log](https://github.com/user-attachments/files/18198854/dmesg.log)
[last_kmsg.log](https://github.com/user-attachments/files/18198917/last_kmsg.log)

**Comment by naz664** [comment]
Device name ?

**Comment by hrzndelta** [comment]
> Device name ?

Samsung SM-A236E | a23xq | A23 5G

**Comment by naz664** [comment]
Okay,
I will give a new build in few hrs

**Comment by naz664** [comment]
Test
https://my-index-azure.vercel.app//boot.img.xz

**Comment by hrzndelta** [comment]
> Test https://my-index-azure.vercel.app//boot.img.xz

it booted, that was fast, thank you
i'll be reporting functions soon
