### ISSUE TITLE
[Request] add AndyYan's patch for tablets

### ISSUE THREAD

**Issue by turbo-boo** [naz664/crDroid_patches#125]
Hi, I found that keyguard blocks rotate in lockscreen. (i.e. forces portrait everytime you open the lockscreen)
This is very bad for tablets, because average user uses landscope mode.

and AndyYan's patch solves this. can you include his patch?
https://github.com/AndyCGYan/lineage_patches_unified/blob/bdbff991a444776d6328d289d668b3fcf7ab9842/patches_platform/frameworks_base/0004-Keyguard-Allow-locking-to-any-rotation-mode.patch

**Comment by monefiera** [comment]
I would like to see this patch implemented too...it would definitely make this GSI more perfect

**Comment by naz664** [comment]
> Hi, I found that keyguard blocks rotate in lockscreen. (i.e. forces portrait everytime you open the lockscreen) This is very bad for tablets, because average user uses landscope mode.
> 
> and AndyYan's patch solves this. can you include his patch? https://github.com/AndyCGYan/lineage_patches_unified/blob/bdbff991a444776d6328d289d668b3fcf7ab9842/patches_platform/frameworks_base/0004-Keyguard-Allow-locking-to-any-rotation-mode.patch

Okay i will add in next update ig
