### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by rlucianord** [naz664/crDroid_patches#14]
I had the 9.3  version installed but when installed this one, it remain on boot loop and nothing come up in the phone

**Comment by naz664** [comment]
Device name ?
Logs ?

**Comment by rlucianord** [comment]
Oneplus Nord N100
Lost the log, I had to reinstall the version 9.3 and fastboot -w to erase
everything.

THanks!

**Comment by naz664** [comment]
Does latest td build or other gsi's with April patch booting ?

**Comment by rlucianord** [comment]
No really, I have tried with  [Pixel](https://github.com/ponces/treble_build_pe/releases/) wich always worked for me, but now it does not.

**Comment by naz664** [comment]
Try this https://github.com/naz664/Test/releases/tag/v2023.07.17-1

**Comment by naz664** [comment]
This issue should have fixed with version 9.7
