### ISSUE TITLE
The mobile phone has no caller ID.

### ISSUE THREAD

**Issue by Libra1236** [naz664/crDroid_patches#15]
I swiped a GSI, and I can make a phone call, but there is no caller ID. The mobile phone is vivo S10.

**Comment by naz664** [comment]
Same behaviour on all gsi's ?

**Comment by Libra1236** [comment]
yes

**Comment by Libra1236** [comment]
I found that vivo has its own IMS.apk, but I can't install it.

**Comment by naz664** [comment]
Test it on td aosp, and report me back 
if the issue exist there
