### ISSUE TITLE
Pls make system on R/W mode 

### ISSUE THREAD

**Issue by dedsecproyt** [naz664/crDroid_patches#17]
I need add this line to build.prop ' persist.camera.HAL3.enabled=1 ' but i have error but system on Reed only mode
![Screenshot_20230514-012755_Material Files](https://github.com/naz664/crDroid_gsi/assets/60039962/21cebf94-b789-496b-b161-b7d3c6e5205a)

**Comment by naz664** [comment]
All varient except slim are R/W
