### ISSUE TITLE
Long screenshot not works Plus and Telegram 

### ISSUE THREAD

**Issue by dedsecproyt** [naz664/crDroid_patches#18]
Pls fix screenshot utillity on Plus and Telegram: when i try to get screenshot in chat or group its willl cancelled [MatLogs.txt](https://github.com/naz664/crDroid_gsi/files/11525263/MatLogs.txt) [ScreenRecord](https://t.me/crDroidAndroid/349954)

**Comment by naz664** [comment]
Works on all other gsi's ?

**Comment by dedsecproyt** [comment]
> Works on all other gsi's ?

I haven't tried, but maybe

**Comment by naz664** [comment]
Check whether it works on this build https://github.com/naz664/Test/releases/tag/v2023.07.17-1

**Comment by dedsecproyt** [comment]
Okey, i will try when I will have it, now it is under repair.....

**Comment by dedsecproyt** [comment]
Okey, i will try when I will have it, now it is under repair.....

**Comment by naz664** [comment]
Ok try version 9.7 instead
