### ISSUE TITLE
Echo on phone calls....

### ISSUE THREAD

**Issue by ArSd-g** [naz664/crDroid_patches#2]
What ever GSI ROM i try i have both of the internal phone mic and bluetooth headset mic ups!!!
This result an horrible echo of my voice when i speak with someone!
This looks like to be a common issue but i can't find a clear explaination of what is happening AND HOW TO FIX THIS!
Please help me! MTK6761 device.
I tried dozen of GSI ROM from A9 to A12= same !!!!

**Comment by naz664** [comment]
If it exist on phh aosp,
may be you can ask phh about it
https://t.me/phhtreble
And attach logs
