### ISSUE TITLE
Samsung AFC not working

### ISSUE THREAD

**Issue by dedsecproyt** [naz664/crDroid_patches#20]
My phone doesn't triggered to AFC fast charge protocol but PD works, I would like you to add fast charge protocol support QC3.0 and Samsung AFC
Device: Samsung Note 20 Ultra
ROM GSI: CRDROID 9.5

**Comment by naz664** [comment]
Does it works on td aosp build ?

**Comment by dedsecproyt** [comment]
> Does it works on td aosp build ?

I did not try because there are no official custom firmwares for my Samsung
Stock kernel with OneUI

**Comment by naz664** [comment]
If it does not work on aosp,
then it will broken on all gsi which use its base.
