### ISSUE TITLE
Error in last update crdroid 9.6

### ISSUE THREAD

**Issue by Lotybr** [naz664/crDroid_patches#23]
I was messing with my poco m5 and in the 9.5 update it was working 100% in the last update the doze feature  and bl hal It wasn't working and yes I also installed it on another device and it got the same error ps: please change the oasp keyboard to Gboard as it was before it's much better

**Comment by naz664** [comment]
Fixed on new update
https://github.com/naz664/crDroid_gsi/releases/tag/v2023.07.21
