### ISSUE TITLE
Broken fingerprint reader on Samsung

### ISSUE THREAD

**Issue by dragbeadle** [naz664/crDroid_patches#25]
The update to version 9.7  (specifically: "crDroid 9.7 (A53-boot) v2023.07.22") has broken the fingerprint reader on my Samsung S22. It was working fine on v9.6 and I think it also had issues on 9.5 but I only flashed that to test the recently fixed bt-audio problem so I didn't pay much attention. Fingerprint also worked fine on the td AOSP GSI that I flashed a few days ago. 

All settings relating to the fingerprint sensor have disappeared from the settings-app. 

I tried enabling or disabling [Phh Treble settings -> Samsung -> "workaround for broken fingerprint"]. That didn't help.

**Comment by naz664** [comment]
Ok
you available on telegram ?

**Comment by naz664** [comment]
Try this build 
https://github.com/naz664/Test/releases/tag/vnosetupwizardtest

**Comment by dragbeadle** [comment]
Yes, in that build fingerprint works again. Thanks!

Could you upload without google services? I use microG myself.

**Comment by naz664** [comment]
Will push a new build tomorrow

**Comment by dragbeadle** [comment]
That would be great, thank you!
