### ISSUE TITLE
Ajuda eu pfv

### ISSUE THREAD

**Issue by Guhxl** [naz664/crDroid_patches#27]
Meu celular a14 5g Android 13 até agora não dá boot em nem uma fixa em loop na tela de boot deixei mais de 1 hora i nada Sabe algum que da para meu celular? Fica igual essa tela aí mais não sai dela....
![Screenshot_20230725_233014_YouTube](https://github.com/naz664/crDroid_gsi/assets/140579906/812072b7-f3a0-4eeb-8672-5c24f0bba640)

**Comment by naz664** [comment]
Can't understand you,
Describe in English.

**Comment by Enzo08012012** [comment]
brickou seu telefone, ou o seu celular não suporta crdroid, eu tentei instalar ancient os, e ficou dando bootloop, recomendo que voce instale outro sistema.
