### ISSUE TITLE
Face recognition issues

### ISSUE THREAD

**Issue by cappuchi** [naz664/crDroid_patches#3]
When going through the Setup Wizard I ran into a problem. It asked me for facial unlocking. The issue which I'm talking about is that it fails. It just asks you for showing your face to the front facing camera, the system scans, it eventually stops at 3/4 of the progress and it fails by returning the error message. And that goes on, and on, and on, and on... that I would even do that for eternity. I couldn't find the skip option, and it made the system being rendered useless, as I couldn't pass any further in the system setup wizard. I don't know if it is my stupidity or just the system's will.

Phone where I was experiencing this issue: Redmi 9A (MT6765)

**Comment by naz664** [comment]
Does this still happens ?
Does it works on other Android13 gsi ?
Using any custom kernel or vendor ?

**Comment by dedsecproyt** [comment]
On my Note 20 Ultra (SM-N986) have same issue
Stock Samsung kernel

**Comment by Kerrnel** [comment]
Y700 Legion - same; just fails (not 3/4). Have to "adb shell pm uninstall --user 0 com.crdroid.faceunlock" to complete setup

**Comment by naz664** [comment]
Does it works on v9.7 ?

**Comment by oneofmanyacdcfanstoo** [comment]
This is still a problem for me too. The only workaround is to factory reset or reflash, and then skip screen lock creation during initial setup.

**Comment by oneofmanyacdcfanstoo** [comment]
> Does this still happens ? Does it works on other Android13 gsi ? Using any custom kernel or vendor ?

This is also a problem on Superior OS and Cherish OS. LineageOS-TD20 works fine because you can skip face unlock.

**Comment by naz664** [comment]
There is an option for skipping faceunlock on setup iirc
