### ISSUE TITLE
Google Setup Wizard no longer included in "slim" build

### ISSUE THREAD

**Issue by PinkSerenity** [naz664/crDroid_patches#34]
As opposed to 9.7, the 9.8 "slim" build does no longer include the Google Setup Wizard and as such restoring Drive backups is no longer possible. Was that a conscious decision? The 9.8 change log refers to a fix for Google Restore (maybe the fix for #30), so it seems unlikely that it was removed from the base ROM.

**Comment by naz664** [comment]
Will add on next update
