### ISSUE TITLE
Bluetooth audio on phone calls doesn´t work

### ISSUE THREAD

**Issue by opa-rudi** [naz664/crDroid_patches#4]
For me it is not possible to switch to bluetooth audio source (headset, car) when calling somebody. Bluetooth audio used by apps like Spotify is working fine.

**Comment by naz664** [comment]
Does this issue exist on other A13 gsi's ?
Like trebleDroid aosp ?

**Comment by opa-rudi** [comment]
This happens also on other Custom ROMS. Everything else works well.

**Comment by opa-rudi** [comment]
I played around a little. Finally the BT audio on phone calls work fine.
