### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by Tomushiki** [naz664/crDroid_patches#40]
When mobile data is turned on, i can't access the internet, same with wifi
Tecno KG5P 
Mt6765

**Comment by naz664** [comment]
Run this on cmd 
"adb shell settings put global restricted_networking_mode 0"
refer this article for more info
https://forum.xda-developers.com/t/gsi-13-lineageos-20-light.4509315/#post-87620773

**Comment by Tomushiki** [comment]
Thank you for the help, sincerely
