### ISSUE TITLE
[crdroid9.10] always on display doesn't work on Redmi K50

### ISSUE THREAD

**Issue by 0123-smallbottle** [naz664/crDroid_patches#44]
always on display doesn't work on Redmi K50
turned on "Force allow Always-On Display"
![Screenshot_20231107-064531_PhhTrebleApp~2](https://github.com/naz664/crDroid_gsi/assets/82559028/f91ce7f4-e758-422a-8947-6412cfbaf382)
the option sill doesn't show up in display>lock screen
![Screenshot_20231107-064822_Google](https://github.com/naz664/crDroid_gsi/assets/82559028/a5e52975-6c38-47eb-ad6a-b39c98acde81)

**Comment by Enzo08012012** [comment]
1 day ago i installed crdroid on my moto g9 play, and always on display was working normaly, but i tried to install root(magisk.zip)   
and it failed, so i reinstaled the custom rom, and now always on display doesnt work for me.

**Comment by 0123-smallbottle** [comment]
> 1 day ago i installed crdroid on my moto g9 play, and always on display was working normaly, but i tried to install root(magisk.zip) and it failed, so i reinstaled the custom rom, and now always on display doesnt work for me.

Thats cool
I install magisk by patching the boot.img
Did you install any modules?

**Comment by naz664** [comment]
If its broken on td aosp,
Then it is expected to have same behaviour on all gsi's based on it
