### ISSUE TITLE
crDroid-10.0-Beta-arm64_bgN-slim-Unofficial.img.xz

### ISSUE THREAD

**Issue by 13didounet** [naz664/crDroid_patches#49]
impossible to install
 google account entry screen not displayed.
runs in a loop

**Comment by naz664** [comment]
Will push a new build with the fix in few hrs

**Comment by 13didounet** [comment]
ok thanks and happy holidays

**Comment by naz664** [comment]
You can try this meanwhile
https://sourceforge.net/projects/gsi-projects/files/A14/crDroid/BETA/launcher-test.img.xz/download

**Comment by 13didounet** [comment]
Thank you, it works.

**Comment by AngelBePro** [comment]
It works, but for me system UI randomly crashes sometimes. Hoping to see a release.

**Comment by naz664** [comment]
On

> It works, but for me system UI randomly crashes sometimes. Hoping to see a release.

On gapps build ?

**Comment by AngelBePro** [comment]
Yes!

**Comment by naz664** [comment]
> Yes!

This build ?
https://sourceforge.net/projects/gsi-projects/files/A14/crDroid/BETA/launcher-test.img.xz/download

**Comment by AngelBePro** [comment]
~Will download and test it!~ Yes, this build.

**Comment by 13didounet** [comment]
impossible to access
 wallpaper style 
message error

**Comment by AngelBePro** [comment]
> ~Will download and test it!~ Yes, this build.

I tought you mean for me to try this build, not if thats the build im talking about so thats why I said I will try it. But my actual answer is "Yes, this build".
