### ISSUE TITLE
Crdroid 10 23/12/2023 slim variant 

### ISSUE THREAD

**Issue by walker425** [naz664/crDroid_patches#53]
I tried the slim variant but I experienced these bugs; Bluetooth is not working in medietake even when I turn on from phh settings, another thing is debug mode is also not working coz the phone is not detected by a PC. Lastly the crdroid settings show system UI error when I tried to customizable features. Anyway I love 💕 ur work and I request u to fix those few bug's for me and this gsi could be my daily driver.

**Comment by naz664** [comment]
Bluetooth issue would have been fixed on latest update
