### ISSUE TITLE
Header image

### ISSUE THREAD

**Issue by Kfox-official** [naz664/crDroid_patches#59]
crDroid-10.0 v2023.12.23 works on Black Shark 3 very well, but i can't select header image form local image.

(Other bugs)
Fingerprint not work
Display lock cover art not work
Back light setting not working

But totally this rom is perfect for me 

![Screenshot_20240102-215325_設定.png](https://github.com/naz664/crDroid_gsi/assets/106442193/0a22d001-b4b7-4f54-9fe1-dd4ccfb2a08e)

**Comment by naz664** [comment]
Source issue,
Might fix with coming update
Fp - device specific 
if its work on td aosp, then it should work on this as well
