### ISSUE TITLE
System Ui not responding buggy message.

### ISSUE THREAD

**Issue by jaefferson** [naz664/crDroid_patches#62]
At times the message appears that the system UI is not responding, sometimes due to a heavy application that I uninstalled and locked the phone, but then unlocks, however the message saying that the application is not responding keeps appearing all the time on the screen, even if I click on wait. The issue is only temporarily resolved after I close the System Interface or restart the system.

![Screenshot_20240103-225540_crDroid Home](https://github.com/naz664/crDroid_gsi/assets/63628793/95c75a76-bc31-4377-8bbd-01fbce32018c)

Thank you.

**Comment by naz664** [comment]
Source issue,
Might fix with next update ig
