### ISSUE TITLE
Tecno Pova 3 (lf7n) Bluetooth issue

### ISSUE THREAD

**Issue by zeleniychupakeps** [naz664/crDroid_patches#63]
I have a problem with Bluetooth on the latest version 10.0 When I try to turn it on, it says “Enabling...” in the top panel, but when I enter the settings it says that it doesn’t turn on. Is it possible to fix this somehow?

![Screenshot_20240109-143052_Настройки](https://github.com/naz664/crDroid_gsi/assets/136248546/2a66a698-7e3b-4b2b-9243-65e3371c5c7a)
![Screenshot_20240109-143054_Настройки](https://github.com/naz664/crDroid_gsi/assets/136248546/65585149-48f9-40f5-8eb6-f025b686e041)

**Comment by naz664** [comment]
Mtk device ?
Does it works on td aosp ?

**Comment by zeleniychupakeps** [comment]
Yes, Mediatek Helio g88
The problem was in the android version. For some reason, bluetooth does not work on Android 14, but it works on Android 13. I had to install version 9.10

**Comment by naz664** [comment]
Check if it's work on this build
https://t.me/naz_dis/96536
