### ISSUE TITLE
SELinux is disabled

### ISSUE THREAD

**Issue by solocotien** [naz664/crDroid_patches#66]
Hello, is there anyway to enable SELinux and set it to Enforcing? My tablet SELinux is disabled after booting this newly installed GSI ROM.

I tried to setenforce to 1 as root but no success.

**Comment by dragbeadle** [comment]
Just to provide a little bit of context: 

Running this GSI on my Samsung S22 (Exynos) SELinux is definitely set to enforcing. Maybe your problem is caused by your tablet's firmware?

**Comment by naz664** [comment]
> Hello, is there anyway to enable SELinux and set it to Enforcing? My tablet SELinux is disabled after booting this newly installed GSI ROM.
> 
> I tried to setenforce to 1 as root but no success.

Using any custom kernel ? the gsi can boot fine in enforcing, looks like its a issue from your side.

**Comment by DanielMcGeeMarin** [comment]
Same issue here, running on Samsung Galaxy S8 ultra running arm64 bvn.

**Comment by naz664** [comment]
Again, not a gsi issue
