### ISSUE TITLE
Can't make calls - phone thinks it's on Airplane Mode when turning phone on

### ISSUE THREAD

**Issue by StupidRepo** [naz664/crDroid_patches#69]
This breaks Zygisk on Magisk as well. To make a call, I now have to enable and disable airplane mode. But doing that doesn't fix Magisk.

I need Magisk & Zygisk so my phone's screen can turn back on from sleep mode. Please fix this ASAP so I can use basic phone functionality. I'm using a Redmi Note 10 5G.

**Comment by naz664** [comment]
What has magisk to do with waking the device ?

**Comment by b1bradders** [comment]
I have to install a brightness module for my GSI

**Comment by b1bradders** [comment]
Well, I seem to have fixed the issue, but now another issue is happening. Give me a minute to make another issue report on GitHub.
