### ISSUE TITLE
A64 Failed resize partition issue

### ISSUE THREAD

**Issue by LinggaCR17** [naz664/crDroid_patches#8]
fastboot delete-logical-partition product ✓
fastboot delete-logical-partition product_a ✓
fastboot delete-logical-partition product_b ✓
fastboot erase system ✓

a64 failed resize partition after:
fastboot flash system system.img (crdroid)

Resizing 'system' FAILED (remote: 'Not enough space to resize partition')
fastboot: error: Command failed

does the next update support lower than 2gb?

**Comment by naz664** [comment]
May be
