### ISSUE TITLE
"SLIM" what does it mean?

### ISSUE THREAD

**Issue by vadimlitvinenko87** [naz664/crDroid_patches#88]
Hi! Seen slim and lite versions of firmware, and can't find any information about slimming. What is cutted off tell me please?

**Comment by vadimlitvinenko87** [comment]
Looks like image recompressed and nothing changed in gapps count. Any advantages for memory and storage usage is present in slim version or it is not affect to android device efficiency? Slim same as normal, and i no need reinstall it for better performance or space economy?

**Comment by naz664** [comment]
> Hi! Seen slim and lite versions of firmware, and can't find any information about slimming. What is cutted off tell me please?

Slim build is a read only (RO) build, which means you wont be able to modify contents inside the system.
If you care about it, you can use normal builds since they are RW.

**Comment by vadimlitvinenko87** [comment]
Thanks.
