### ISSUE TITLE
manifests broken?

### ISSUE THREAD

**Issue by xlibun** [naz664/crDroid_patches#89]
when I try to sync the repo with your manifests, it just throws an error 

`duplicate path external/mockito-kotlin in ../crDroid/.repo/manifest.xml`

**Comment by naz664** [comment]
Revert this commit 
https://github.com/naz664/treble_manifest/commit/7c26417290dd1587c24205f497fc0afff6e49649

or drop file named tmp-gg-r17.xml from .repo/local_manifests

**Comment by xlibun** [comment]
thank you
