### ISSUE TITLE
Fingerprint sensor on A50

### ISSUE THREAD

**Issue by opa-rudi** [naz664/crDroid_patches#9]
Fingerprint sensor on Galaxy A50 doesn´t work in 9.1 and 9.2. It only works in 8.13

**Comment by naz664** [comment]
Does it works on any other Android 13 gsi ?

**Comment by opa-rudi** [comment]
With SparkOS it also doesn´t work in Android 13 version. The only version were everything works is CRDroid 8.13 (but also have some freezing issue with specific apps sometimes, but the only Custom ROM for daily work).

**Comment by naz664** [comment]
Does it works on trebleDroid gsi ?

**Comment by opa-rudi** [comment]
I haven´t tested it. Sry.

**Comment by naz664** [comment]
Test and report me back

**Comment by naz664** [comment]
Test it on latest build
https://github.com/naz664/crDroid_gsi/releases/tag/v2023.07.21

**Comment by opa-rudi** [comment]
Doesn´t work with current build. App also crashes when pushing the finger on the sensor when setting up the fingerprints.

**Comment by naz664** [comment]
Try this build
https://github.com/naz664/crDroid_gsi/issues/25#issuecomment-1646600349

**Comment by opa-rudi** [comment]
Sadly, the same problem. I´ll stay with 8.13

regards!

**Comment by opa-rudi** [comment]
Hi Nazim,

Just wanted to know if there is a new gsi crdroid in the near future?

Kind regards!
Michael
