### ISSUE TITLE
New update Break WiFi

### ISSUE THREAD

**Issue by weskerty** [naz664/crDroid_patches#96]
At 10.5 the wifi connects and marks that it has a connection, but no app can access it. Version 10.1 works correctly.
Nokia G20 MT6765

**Comment by weskerty** [comment]
[logs-2024-05-16-02-17-50.zip](https://github.com/naz664/crDroid_gsi/files/15330445/logs-2024-05-16-02-17-50.zip)

**Comment by nickpapoutsis** [comment]
Same problem on a Teclast T40s

**Comment by weskerty** [comment]
> Same problem on a Teclast T40s

It's not the Wi-Fi. Related issue: #105
solved with:
`adb shell settings put global restricted_networking_mode 0`
