### ISSUE TITLE
[REQUEST] Sign the build with custom keys

### ISSUE THREAD

**Issue by bittergg** [naz664/crDroid_patches#99]
Hello, 
Recently the Play Integrity API has changed in a way it detects custom ROMs, and for it to currently pass the device integrity the build must be signed by keys that havent been banned. People on XDA's PlayIntegrityFIX have been successful with passing device by signing their builds, therefore i request for the next builds of this GSI rom to be signed by non-test/banned keys.

**Comment by bittergg** [comment]
After signing the build myself, i can confirm that signing the gsi build makes the device pass Play Integrity. 
The signed image can be dirty flashed over an unsigned image on android 13+.

**Comment by giving-sesame** [comment]
> After signing the build myself, i can confirm that signing the gsi build makes the device pass Play Integrity. The signed image can be dirty flashed over an unsigned image on android 13+.

I have the same problem. Could you please give me a link to instructions how to sign the build by myself?

**Comment by Sherirk** [comment]
> > After signing the build myself, i can confirm that signing the gsi build makes the device pass Play Integrity. The signed image can be dirty flashed over an unsigned image on android 13+.
> 
> I have the same problem. Could you please give me a link to instructions how to sign the build by myself?

You can follow the build instructions from this repo's README, but before the "Generating Rom Makefile" step you gotta apply [this](https://github.com/306bobby-android/crDroid-build-signed-script). I believe you can even do the signing process after creating the rom makefile and before the "Compilation" step but not sure.

**Comment by giving-sesame** [comment]
> You can follow the build instructions from this repo's README, but before the "Generating Rom Makefile" step you gotta apply [this](https://github.com/306bobby-android/crDroid-build-signed-script). I believe you can even do the signing process after creating the rom makefile and before the "Compilation" step but not sure.

Thank you very much for hints!
